-- 围棋对弈平台 - Supabase 数据库 Schema
-- 在 Supabase SQL Editor 中执行

-- 房间表
CREATE TABLE rooms (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  password TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'waiting',
  board JSONB NOT NULL DEFAULT '[]',
  current_turn TEXT NOT NULL DEFAULT 'black',
  ko_position JSONB,
  last_move JSONB,
  winner TEXT,
  result TEXT,
  started_at BIGINT,
  created_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT
);

-- 玩家表
CREATE TABLE players (
  id TEXT PRIMARY KEY,
  room_password TEXT NOT NULL REFERENCES rooms(password) ON DELETE CASCADE,
  nickname TEXT NOT NULL,
  role TEXT NOT NULL,
  color TEXT,
  is_ready BOOLEAN NOT NULL DEFAULT FALSE,
  connected BOOLEAN NOT NULL DEFAULT TRUE,
  time_remaining BIGINT NOT NULL DEFAULT 1200000,
  byoyomi_count INTEGER NOT NULL DEFAULT 3,
  is_in_byoyomi BOOLEAN NOT NULL DEFAULT FALSE,
  created_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT
);

-- 棋步记录表
CREATE TABLE moves (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_password TEXT NOT NULL REFERENCES rooms(password) ON DELETE CASCADE,
  position JSONB NOT NULL,
  color TEXT NOT NULL,
  move_number INTEGER NOT NULL,
  captured_stones JSONB,
  timestamp BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT
);

-- 聊天消息表
CREATE TABLE chat_messages (
  id TEXT PRIMARY KEY,
  room_password TEXT NOT NULL REFERENCES rooms(password) ON DELETE CASCADE,
  sender_id TEXT NOT NULL,
  sender_nickname TEXT NOT NULL,
  content TEXT NOT NULL,
  timestamp BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT
);

-- 索引
CREATE INDEX idx_players_room ON players(room_password);
CREATE INDEX idx_moves_room ON moves(room_password);
CREATE INDEX idx_messages_room ON chat_messages(room_password);

-- 启用 Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE rooms;
ALTER PUBLICATION supabase_realtime ADD TABLE players;
ALTER PUBLICATION supabase_realtime ADD TABLE moves;
ALTER PUBLICATION supabase_realtime ADD TABLE chat_messages;

-- RLS 策略（简化版：允许所有读写，生产环境需限制）
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE players ENABLE ROW LEVEL SECURITY;
ALTER TABLE moves ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;

-- 允许所有操作（开发用）
CREATE POLICY "Allow all access to rooms" ON rooms FOR ALL USING TRUE WITH CHECK TRUE;
CREATE POLICY "Allow all access to players" ON players FOR ALL USING TRUE WITH CHECK TRUE;
CREATE POLICY "Allow all access to moves" ON moves FOR ALL USING TRUE WITH CHECK TRUE;
CREATE POLICY "Allow all access to chat_messages" ON chat_messages FOR ALL USING TRUE WITH CHECK TRUE;